# set up the nginx container
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./sites-available/default:/etc/nginx/sites-available/default
    - ./sites-available/default:/etc/nginx/sites-enabled/default

    - ./logs/nginx-error.log:/var/log/nginx/error.log
    - ./logs/nginx-access.log:/var/log/nginx/access.log

    - ./public_html:/var/www/html

# set up the php container
php:
  image: php:7.4-fpm
  ports:
    - "9000:9000"
  volumes:
    - ./public_html:/var/www/html