version: '2'

services:
  # set up the nginx container
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./sites-available/default:/etc/nginx/sites-available/default
      - ./sites-available/default:/etc/nginx/sites-enabled/default

      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log

      - ./public_html:/var/www/html
    networks:
      - code-network
  # set up the php container
  php:
    image: php:fpm
    restart: always
    volumes:
      - ./public_html:/var/www/html
    networks:
      - code-network

networks:
  code-network:
      driver: bridge