version: '3'

services:
  # set up the nginx container
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NAME}_LEMP_nginx
    restart: always
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./sites-available/default.conf:/etc/nginx/sites-available/default.conf
      - ./sites-available/default.conf:/etc/nginx/conf.d/default.conf

      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log

      - ./public_html:/var/www/html
    networks:
      - lemp-network

  # set up the php container
  php:
    image: php:fpm
    container_name: ${CONTAINER_NAME}_LEMP_php
    restart: always
    volumes:
      - ./public_html:/var/www/html
    networks:
      - lemp-network

  # set up database
  mariadb:
    image: mariadb:latest
    container_name: ${CONTAINER_NAME}_LEMP_mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - lemp-network

networks:
  lemp-network:
      driver: bridge